In [26]:
import numpy as np

X = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90],
              [15, 25, 35]])

# Drill 1: rows where col index 1 > 40
print(X[X[:,1]>40])
# Drill 2: standardize X column-wise — one line
standard=(X-X.mean(axis=0))/X.std(axis=0)
print(standard)
# Drill 3: X.sum(axis=1) — predict shape and values as comment, then run
print(X.sum(axis=1))   # (4,)
# Drill 4: replace every value below 30 with 0, keep rest — one line
new=np.where(X<30,0,X)
print(new)
# Drill 5: count rows where at least one value > 80
print(np.sum(np.any(X>80,axis=1)))




[[40 50 60]
 [70 80 90]]
[[-0.99724137 -0.99724137 -0.99724137]
 [ 0.26243194  0.26243194  0.26243194]
 [ 1.52210526  1.52210526  1.52210526]
 [-0.78729582 -0.78729582 -0.78729582]]
[ 60 150 240  75]
[[ 0  0 30]
 [40 50 60]
 [70 80 90]
 [ 0  0 35]]
1


In [13]:
import numpy as np
Y=np.array([ 60 ,150 ,240 , 75])
Y.shape

(4,)

In [28]:
inputs  = np.array([0.8, 0.2, 0.5, 0.1])
weights = np.array([0.4, 0.6, 0.1, 0.9])
bias    = 0.5
np.dot(inputs,weights) + bias

np.float64(1.08)

In [35]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])   # shape (3,2)

W = np.array([[0.1, 0.2, 0.3],
              [0.4, 0.5, 0.6]])   # shape (2,3)
v=X@W
print(v)
np.linalg.norm(v[1,])

[[0.9 1.2 1.5]
 [1.9 2.6 3.3]
 [2.9 4.  5.1]]


np.float64(4.610856753359402)

In [36]:
A = np.random.randn(4, 3)
print((A @ A.T).shape)
print((A.T @ A).shape)

(4, 4)
(3, 3)
