In [2]:
import numpy as np
data = np.array([[170, 65, 1],     # height, weight, label
                 [155, 48, 0],
                 [999, 80, 1],     # corrupted height — outlier
                 [160, 55, 0],
                 [182, 90, 1]])

# Step 1: find outlier rows (height > 200 is unrealistic)
valid_mask = data[:, 0] < 200
clean = data[valid_mask]            # drops the 999 row

# Step 2: separate features and labels
X = clean[:, :2]                   # first two columns
y = clean[:, 2]                    # last column

# Step 3: standardize X
X_std = (X - X.mean(axis=0)) / X.std(axis=0)

# Step 4: encode: tall person (height > mean) gets flag
mean_height = X[:, 0].mean()
tall_flag = np.where(X[:, 0] > mean_height, 1, 0)

In [13]:
students = np.array([[85, 90, 78],
                     [42, 55, 60],
                     [90, 88, 95],
                     [30, 45, 50],
                     [75, 80, 85]])
# rows = students, cols = [math, science, english]
print(students[students[:,0] > 70])
print(np.any(students < 60,axis=1))

print(np.sum(np.any(students < 60, axis=1)))

[[85 90 78]
 [90 88 95]
 [75 80 85]]
[False  True False  True False]
2
