In [5]:
import numpy as np
arr=np.zeros((4,5))
arr[:,2]=7
arr.shape
arr.dtype

dtype('float64')

In [46]:
n=np.arange(1,26)
new=n.reshape(5,5)
print(new[0]) 
print(new[4]) 
print(new[:, 0])




[1 2 3 4 5]
[21 22 23 24 25]
[ 1  6 11 16 21]


In [24]:
lin=np.linspace(0,100,10)
lin.dtype

dtype('float64')

In [26]:
X=([ 4,  9, 14, 19, 24])
b = X[0]
b[0] = 999
print(X[0, 0])   # 999 — original changed!

c = X[0].copy()  # safe independent copy

TypeError: 'int' object does not support item assignment

In [30]:
import numpy as np

X = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

b = X[0]        # b is a VIEW of row index 0 → [10, 20, 30]

In [31]:
c = X[1].copy()   # c is an independent COPY of row index 1
c[0] = -5
print(X)          # X is untouched — still has 40 in that spot
print(c)          # [-5, 50, 60]

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[-5 50 60]


In [45]:
Y=np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
z=Y[2]
Y[2]=129
print(z)


[129 129 129]


In [38]:
#correction
z=Y[2].copy()
Y[2]=130
print(z)

[70 80 90]


In [67]:
s=np.arange(12)
si=s.reshape(3, 4)
print(si)
si.max()
si.sum(axis=0)
si.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [63]:
scores = np.array([[80, 92, 70], [95, 60, 88], [72, 85, 91]])
students=scores.mean(axis=1)
print(students)
sub=scores.mean(axis=0)
print(sub)
top=scores.argmax(axis=0)
print(top)


[80.66666667 81.         82.66666667]
[82.33333333 79.         83.        ]
[1 0 2]


In [70]:
data = np.array([[170, 65],     # person 0: height, weight
                 [160, 70],
                 [180, 80]])
bw=(data - data.mean(axis=0)) / data.std(axis=0)
print(bw.mean(axis=0))
print(bw)


[ 0.00000000e+00 -8.14163551e-16]
[[ 0.         -1.06904497]
 [-1.22474487 -0.26726124]
 [ 1.22474487  1.33630621]]


In [68]:
si = np.arange(12).reshape(3, 4)


print(si.sum())
print(si.sum(axis=0), si.sum(axis=0).shape)
print(si.sum(axis=1), si.sum(axis=1).shape)

66
[12 15 18 21] (4,)
[ 6 22 38] (3,)
